name: main
type: pass
steps:
  - name: rand
    type: function
    source: rand
    inputMappings:
      - target: count
        source: INPUT.count
  - name: my_foreach
    type: foreach
    inputMappings:
      - target: x
        source: LOCAL.rand_result[*]
    task:
      name: square
      type: function
      source: square
    outputMappings:
      - target: result
        source: LOCAL[*].square_result
outputMappings:
  - target: result
    source: LOCAL.result
      
# rand ------------> square 

# The final output will be {"result": [rand[0]*rand[0], rand[1]*rand[1], ...]}